name: Technology of the Month
url: http://pshendry.github.io/totm
description: Every month, a new overview of a language, engine, framework, or other software development technology

permalink: /:title/
paginate: 10
highlighter: pygments

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
